### ISSUE TITLE
No preview

### ISSUE THREAD

**Issue by AlexAegis** [jaime-olivares/vscode-yuml#57] opened 2019-02-27 20:21 UTC
Just downloaded the extension on the newest vs code version 1.31.1, and when opening a yuml file a 'missing image' icon shows in the diagram tab. I tried to add the 'class' snippet to see if it does anything but no.

![image](https://user-images.githubusercontent.com/16900547/53520181-57620f00-3ad5-11e9-839e-01cbf3717d1e.png)

**Comment by jaime-olivares** [comment] 2019-02-27 20:24
This is a duplicate of #56 

Did you try to save the file, even with a slight modification like a whitespace?

**Closed by jaime-olivares** 2019-02-27 20:24 UTC
Labels: duplicate

**Comment by AlexAegis** [comment] 2019-02-27 21:10
Yes I did. (lines 11-13 are the remnants of this)

**Comment by jaime-olivares** [comment] 2019-03-05 05:30
Please have a look at the recently published version (3.4). If there is a syntax in your code, it will be shown rather than the undesired icon.
