### ISSUE TITLE
Messages arrows not rendered in sequence diagram

### ISSUE THREAD

**Issue by Narayane** [jaime-olivares/vscode-yuml#50] opened 2018-10-15 15:43 UTC
Hi,

It seems messages and message responses arrows are not currently rendering when I visualize a sequence diagram. I use the yUML plugin v3.1.2 and VS Code v1.28.0.

![capture d ecran 2018-10-15 a 17 38 41](https://user-images.githubusercontent.com/4921308/46961717-ae74c380-d0a1-11e8-99c2-004929b155de.png)

Thanks

**Comment by aduh95** [comment] 2018-10-15 15:50
Duplicate of https://github.com/jaime-olivares/yuml-diagram/issues/10

**Closed** 2019-01-30 15:30 UTC
